version: '3.9'

# Define internal network that has no internet access
networks:
  internal:
    driver: bridge
    internal: true
  default:
    driver: bridge

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_storage:/data
    networks:
      - default
      - internal

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - default
      - internal

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - default
      - internal


  base:
    image: base:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile.base
    depends_on:
      - python-base
    networks:
      - default
      - internal

  python-base:
    image: python-base:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile.python-base
    networks:
      - default
      - internal

  ml-worker:
    image: ml:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile.worker
      extra_hosts:
        - "licensing.scitools.com:127.0.0.1"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - rabbitmq
      - redis
      - minio
      - python-base
    networks:
      - default
      - internal


  api:
    image: application:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile.api
      extra_hosts:
        - "licensing.scitools.com:127.0.0.1"
    ports:
      - "8000:8000"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - STILICENSE=/root/.config/SciTools/License.conf
    depends_on:
      - ml-worker
      - minio
      - rabbitmq
      - redis
      - base
    networks:
      - default
      - internal

volumes:
  minio_storage:
  redis_data: